---

- hosts: homelab

  vars:
    application: syncthing

    docker_network: "{{ networks.pub }}"

  tasks:
    - name: Create config folders
      ansible.builtin.file:
        path: "{{ common_directory_backup }}/{{ application }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0751"

    - name: Create container
      ansible.builtin.include_role:
        name: docker_container
      vars:
        image: ghcr.io/syncthing/syncthing:1.29.3
        ipv4_address: "{{ docker_network.prefix }}.249"
        env:
          PUID: "{{ common_user_id | string }}"
          PGID: "{{ common_group_id | string }}"
        volumes:
          - "{{ common_directory_backup }}/{{ application }}:/var/syncthing"
        traefik:
          - port: 8384
        blackbox:
          path: /rest/noauth/health
