---

- hosts: homelab

  vars:
    application: syncthing

    docker_network: "{{ networks.pub }}"

  tasks:
    - name: Create config folders
      ansible.builtin.file:
        path: "{{ common_directory_backup }}/{{ application }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0751"

    - name: Create container
      ansible.builtin.include_role:
        name: docker_container
      vars:
        image: ghcr.io/syncthing/syncthing:1.29.3
        env:
          PUID: "{{ common_user_id | string }}"
          PGID: "{{ common_group_id | string }}"
        volumes:
          - "{{ common_directory_backup }}/{{ application }}:/var/syncthing"
        traefik:
          -
            port: 8384
          -
            name: "{{ application }}-tcp"
            port: 22000
            type: tcp
          -
            name: "{{ application }}-udp"
            port: 22000
            type: udp
        blackbox:
          path: /rest/noauth/health
