#!/usr/bin/with-contenv bash

# required for the cert to work after restart
sqlite3 /config/Duplicati-server.sqlite "UPDATE Option SET Value='' WHERE Name='server-ssl-certificate';"

cd /app/duplicati || exit

exec \
	s6-setuidgid abc mono Duplicati.Server.exe \
	--webservice-interface=any --server-datafolder=/config --webservice-allowed-hostnames=* $CLI_ARGS
